apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "web.procycla-web.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web-clusterip
            port:
              number: 80
  - host: "api.procycla-web.com"
    http:
      paths:
      - pathType: Prefix
        path: "/backend/"
        backend:
          service:
            name: api-clusterip
            port:
              number: 3010